package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class AppPlatformDocTypeRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.appdocTypeRelationID
     *
     * @mbg.generated
     */
    private Long appdocTypeRelationID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.appdocTypeRelationGuid
     *
     * @mbg.generated
     */
    private String appdocTypeRelationGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.appId
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.docTypeId
     *
     * @mbg.generated
     */
    private Long docTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.downloadFlag
     *
     * @mbg.generated
     */
    private Integer downloadFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.uploadFlag
     *
     * @mbg.generated
     */
    private Integer uploadFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.deleteFlag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.isBoardCast
     *
     * @mbg.generated
     */
    private Boolean isBoardCast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appplatformdoctyperelation.boardCastCount
     *
     * @mbg.generated
     */
    private Long boardCastCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.appdocTypeRelationID
     *
     * @return the value of appplatformdoctyperelation.appdocTypeRelationID
     *
     * @mbg.generated
     */
    public Long getAppdocTypeRelationID() {
        return appdocTypeRelationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.appdocTypeRelationID
     *
     * @param appdocTypeRelationID the value for appplatformdoctyperelation.appdocTypeRelationID
     *
     * @mbg.generated
     */
    public void setAppdocTypeRelationID(Long appdocTypeRelationID) {
        this.appdocTypeRelationID = appdocTypeRelationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.appdocTypeRelationGuid
     *
     * @return the value of appplatformdoctyperelation.appdocTypeRelationGuid
     *
     * @mbg.generated
     */
    public String getAppdocTypeRelationGuid() {
        return appdocTypeRelationGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.appdocTypeRelationGuid
     *
     * @param appdocTypeRelationGuid the value for appplatformdoctyperelation.appdocTypeRelationGuid
     *
     * @mbg.generated
     */
    public void setAppdocTypeRelationGuid(String appdocTypeRelationGuid) {
        this.appdocTypeRelationGuid = appdocTypeRelationGuid == null ? null : appdocTypeRelationGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.appId
     *
     * @return the value of appplatformdoctyperelation.appId
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.appId
     *
     * @param appId the value for appplatformdoctyperelation.appId
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.docTypeId
     *
     * @return the value of appplatformdoctyperelation.docTypeId
     *
     * @mbg.generated
     */
    public Long getDocTypeId() {
        return docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.docTypeId
     *
     * @param docTypeId the value for appplatformdoctyperelation.docTypeId
     *
     * @mbg.generated
     */
    public void setDocTypeId(Long docTypeId) {
        this.docTypeId = docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.downloadFlag
     *
     * @return the value of appplatformdoctyperelation.downloadFlag
     *
     * @mbg.generated
     */
    public Integer getDownloadFlag() {
        return downloadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.downloadFlag
     *
     * @param downloadFlag the value for appplatformdoctyperelation.downloadFlag
     *
     * @mbg.generated
     */
    public void setDownloadFlag(Integer downloadFlag) {
        this.downloadFlag = downloadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.uploadFlag
     *
     * @return the value of appplatformdoctyperelation.uploadFlag
     *
     * @mbg.generated
     */
    public Integer getUploadFlag() {
        return uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.uploadFlag
     *
     * @param uploadFlag the value for appplatformdoctyperelation.uploadFlag
     *
     * @mbg.generated
     */
    public void setUploadFlag(Integer uploadFlag) {
        this.uploadFlag = uploadFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.deleteFlag
     *
     * @return the value of appplatformdoctyperelation.deleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.deleteFlag
     *
     * @param deleteFlag the value for appplatformdoctyperelation.deleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.isActive
     *
     * @return the value of appplatformdoctyperelation.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.isActive
     *
     * @param isActive the value for appplatformdoctyperelation.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.createTime
     *
     * @return the value of appplatformdoctyperelation.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.createTime
     *
     * @param createTime the value for appplatformdoctyperelation.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.updateTime
     *
     * @return the value of appplatformdoctyperelation.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.updateTime
     *
     * @param updateTime the value for appplatformdoctyperelation.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.isBoardCast
     *
     * @return the value of appplatformdoctyperelation.isBoardCast
     *
     * @mbg.generated
     */
    public Boolean getIsBoardCast() {
        return isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.isBoardCast
     *
     * @param isBoardCast the value for appplatformdoctyperelation.isBoardCast
     *
     * @mbg.generated
     */
    public void setIsBoardCast(Boolean isBoardCast) {
        this.isBoardCast = isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appplatformdoctyperelation.boardCastCount
     *
     * @return the value of appplatformdoctyperelation.boardCastCount
     *
     * @mbg.generated
     */
    public Long getBoardCastCount() {
        return boardCastCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appplatformdoctyperelation.boardCastCount
     *
     * @param boardCastCount the value for appplatformdoctyperelation.boardCastCount
     *
     * @mbg.generated
     */
    public void setBoardCastCount(Long boardCastCount) {
        this.boardCastCount = boardCastCount;
    }
}