package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class CustomerDbList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourceClassName
     *
     * @mbg.generated
     */
    private String dataSourceClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourceUser
     *
     * @mbg.generated
     */
    private String dataSourceUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourcePassword
     *
     * @mbg.generated
     */
    private String dataSourcePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourceDataBaseName
     *
     * @mbg.generated
     */
    private String dataSourceDataBaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourcePortNumber
     *
     * @mbg.generated
     */
    private Long dataSourcePortNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dataSourceServerName
     *
     * @mbg.generated
     */
    private String dataSourceServerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.dbTypeNum
     *
     * @mbg.generated
     */
    private Long dbTypeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customerdblist.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.id
     *
     * @return the value of customerdblist.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.id
     *
     * @param id the value for customerdblist.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.guid
     *
     * @return the value of customerdblist.guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.guid
     *
     * @param guid the value for customerdblist.guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourceClassName
     *
     * @return the value of customerdblist.dataSourceClassName
     *
     * @mbg.generated
     */
    public String getDataSourceClassName() {
        return dataSourceClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourceClassName
     *
     * @param dataSourceClassName the value for customerdblist.dataSourceClassName
     *
     * @mbg.generated
     */
    public void setDataSourceClassName(String dataSourceClassName) {
        this.dataSourceClassName = dataSourceClassName == null ? null : dataSourceClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourceUser
     *
     * @return the value of customerdblist.dataSourceUser
     *
     * @mbg.generated
     */
    public String getDataSourceUser() {
        return dataSourceUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourceUser
     *
     * @param dataSourceUser the value for customerdblist.dataSourceUser
     *
     * @mbg.generated
     */
    public void setDataSourceUser(String dataSourceUser) {
        this.dataSourceUser = dataSourceUser == null ? null : dataSourceUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourcePassword
     *
     * @return the value of customerdblist.dataSourcePassword
     *
     * @mbg.generated
     */
    public String getDataSourcePassword() {
        return dataSourcePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourcePassword
     *
     * @param dataSourcePassword the value for customerdblist.dataSourcePassword
     *
     * @mbg.generated
     */
    public void setDataSourcePassword(String dataSourcePassword) {
        this.dataSourcePassword = dataSourcePassword == null ? null : dataSourcePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourceDataBaseName
     *
     * @return the value of customerdblist.dataSourceDataBaseName
     *
     * @mbg.generated
     */
    public String getDataSourceDataBaseName() {
        return dataSourceDataBaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourceDataBaseName
     *
     * @param dataSourceDataBaseName the value for customerdblist.dataSourceDataBaseName
     *
     * @mbg.generated
     */
    public void setDataSourceDataBaseName(String dataSourceDataBaseName) {
        this.dataSourceDataBaseName = dataSourceDataBaseName == null ? null : dataSourceDataBaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourcePortNumber
     *
     * @return the value of customerdblist.dataSourcePortNumber
     *
     * @mbg.generated
     */
    public Long getDataSourcePortNumber() {
        return dataSourcePortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourcePortNumber
     *
     * @param dataSourcePortNumber the value for customerdblist.dataSourcePortNumber
     *
     * @mbg.generated
     */
    public void setDataSourcePortNumber(Long dataSourcePortNumber) {
        this.dataSourcePortNumber = dataSourcePortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dataSourceServerName
     *
     * @return the value of customerdblist.dataSourceServerName
     *
     * @mbg.generated
     */
    public String getDataSourceServerName() {
        return dataSourceServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dataSourceServerName
     *
     * @param dataSourceServerName the value for customerdblist.dataSourceServerName
     *
     * @mbg.generated
     */
    public void setDataSourceServerName(String dataSourceServerName) {
        this.dataSourceServerName = dataSourceServerName == null ? null : dataSourceServerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.remark
     *
     * @return the value of customerdblist.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.remark
     *
     * @param remark the value for customerdblist.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.dbTypeNum
     *
     * @return the value of customerdblist.dbTypeNum
     *
     * @mbg.generated
     */
    public Long getDbTypeNum() {
        return dbTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.dbTypeNum
     *
     * @param dbTypeNum the value for customerdblist.dbTypeNum
     *
     * @mbg.generated
     */
    public void setDbTypeNum(Long dbTypeNum) {
        this.dbTypeNum = dbTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.isActive
     *
     * @return the value of customerdblist.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.isActive
     *
     * @param isActive the value for customerdblist.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.createTime
     *
     * @return the value of customerdblist.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.createTime
     *
     * @param createTime the value for customerdblist.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customerdblist.updateTime
     *
     * @return the value of customerdblist.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customerdblist.updateTime
     *
     * @param updateTime the value for customerdblist.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}