package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class DBUpgradeHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.nodeDbUpgradeHIstoryId
     *
     * @mbg.generated
     */
    private Long nodeDbUpgradeHIstoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.nodeDbGuid
     *
     * @mbg.generated
     */
    private String nodeDbGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.nodeDbName
     *
     * @mbg.generated
     */
    private String nodeDbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.fromPlatformDbVersion
     *
     * @mbg.generated
     */
    private Long fromPlatformDbVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.toPlatformDbVersion
     *
     * @mbg.generated
     */
    private Long toPlatformDbVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.upgradeTime
     *
     * @mbg.generated
     */
    private Date upgradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.currentPlatformUser
     *
     * @mbg.generated
     */
    private Long currentPlatformUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.platformUserLoginName
     *
     * @mbg.generated
     */
    private String platformUserLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.platformUserName
     *
     * @mbg.generated
     */
    private String platformUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.platformHostGuid
     *
     * @mbg.generated
     */
    private String platformHostGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.nodeDbUpgradeHIstoryGuid
     *
     * @mbg.generated
     */
    private String nodeDbUpgradeHIstoryGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbupgradehistory.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.nodeDbUpgradeHIstoryId
     *
     * @return the value of dbupgradehistory.nodeDbUpgradeHIstoryId
     *
     * @mbg.generated
     */
    public Long getNodeDbUpgradeHIstoryId() {
        return nodeDbUpgradeHIstoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.nodeDbUpgradeHIstoryId
     *
     * @param nodeDbUpgradeHIstoryId the value for dbupgradehistory.nodeDbUpgradeHIstoryId
     *
     * @mbg.generated
     */
    public void setNodeDbUpgradeHIstoryId(Long nodeDbUpgradeHIstoryId) {
        this.nodeDbUpgradeHIstoryId = nodeDbUpgradeHIstoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.nodeDbGuid
     *
     * @return the value of dbupgradehistory.nodeDbGuid
     *
     * @mbg.generated
     */
    public String getNodeDbGuid() {
        return nodeDbGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.nodeDbGuid
     *
     * @param nodeDbGuid the value for dbupgradehistory.nodeDbGuid
     *
     * @mbg.generated
     */
    public void setNodeDbGuid(String nodeDbGuid) {
        this.nodeDbGuid = nodeDbGuid == null ? null : nodeDbGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.nodeDbName
     *
     * @return the value of dbupgradehistory.nodeDbName
     *
     * @mbg.generated
     */
    public String getNodeDbName() {
        return nodeDbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.nodeDbName
     *
     * @param nodeDbName the value for dbupgradehistory.nodeDbName
     *
     * @mbg.generated
     */
    public void setNodeDbName(String nodeDbName) {
        this.nodeDbName = nodeDbName == null ? null : nodeDbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.fromPlatformDbVersion
     *
     * @return the value of dbupgradehistory.fromPlatformDbVersion
     *
     * @mbg.generated
     */
    public Long getFromPlatformDbVersion() {
        return fromPlatformDbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.fromPlatformDbVersion
     *
     * @param fromPlatformDbVersion the value for dbupgradehistory.fromPlatformDbVersion
     *
     * @mbg.generated
     */
    public void setFromPlatformDbVersion(Long fromPlatformDbVersion) {
        this.fromPlatformDbVersion = fromPlatformDbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.toPlatformDbVersion
     *
     * @return the value of dbupgradehistory.toPlatformDbVersion
     *
     * @mbg.generated
     */
    public Long getToPlatformDbVersion() {
        return toPlatformDbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.toPlatformDbVersion
     *
     * @param toPlatformDbVersion the value for dbupgradehistory.toPlatformDbVersion
     *
     * @mbg.generated
     */
    public void setToPlatformDbVersion(Long toPlatformDbVersion) {
        this.toPlatformDbVersion = toPlatformDbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.upgradeTime
     *
     * @return the value of dbupgradehistory.upgradeTime
     *
     * @mbg.generated
     */
    public Date getUpgradeTime() {
        return upgradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.upgradeTime
     *
     * @param upgradeTime the value for dbupgradehistory.upgradeTime
     *
     * @mbg.generated
     */
    public void setUpgradeTime(Date upgradeTime) {
        this.upgradeTime = upgradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.currentPlatformUser
     *
     * @return the value of dbupgradehistory.currentPlatformUser
     *
     * @mbg.generated
     */
    public Long getCurrentPlatformUser() {
        return currentPlatformUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.currentPlatformUser
     *
     * @param currentPlatformUser the value for dbupgradehistory.currentPlatformUser
     *
     * @mbg.generated
     */
    public void setCurrentPlatformUser(Long currentPlatformUser) {
        this.currentPlatformUser = currentPlatformUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.platformUserLoginName
     *
     * @return the value of dbupgradehistory.platformUserLoginName
     *
     * @mbg.generated
     */
    public String getPlatformUserLoginName() {
        return platformUserLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.platformUserLoginName
     *
     * @param platformUserLoginName the value for dbupgradehistory.platformUserLoginName
     *
     * @mbg.generated
     */
    public void setPlatformUserLoginName(String platformUserLoginName) {
        this.platformUserLoginName = platformUserLoginName == null ? null : platformUserLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.platformUserName
     *
     * @return the value of dbupgradehistory.platformUserName
     *
     * @mbg.generated
     */
    public String getPlatformUserName() {
        return platformUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.platformUserName
     *
     * @param platformUserName the value for dbupgradehistory.platformUserName
     *
     * @mbg.generated
     */
    public void setPlatformUserName(String platformUserName) {
        this.platformUserName = platformUserName == null ? null : platformUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.platformHostGuid
     *
     * @return the value of dbupgradehistory.platformHostGuid
     *
     * @mbg.generated
     */
    public String getPlatformHostGuid() {
        return platformHostGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.platformHostGuid
     *
     * @param platformHostGuid the value for dbupgradehistory.platformHostGuid
     *
     * @mbg.generated
     */
    public void setPlatformHostGuid(String platformHostGuid) {
        this.platformHostGuid = platformHostGuid == null ? null : platformHostGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.comments
     *
     * @return the value of dbupgradehistory.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.comments
     *
     * @param comments the value for dbupgradehistory.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.nodeDbUpgradeHIstoryGuid
     *
     * @return the value of dbupgradehistory.nodeDbUpgradeHIstoryGuid
     *
     * @mbg.generated
     */
    public String getNodeDbUpgradeHIstoryGuid() {
        return nodeDbUpgradeHIstoryGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.nodeDbUpgradeHIstoryGuid
     *
     * @param nodeDbUpgradeHIstoryGuid the value for dbupgradehistory.nodeDbUpgradeHIstoryGuid
     *
     * @mbg.generated
     */
    public void setNodeDbUpgradeHIstoryGuid(String nodeDbUpgradeHIstoryGuid) {
        this.nodeDbUpgradeHIstoryGuid = nodeDbUpgradeHIstoryGuid == null ? null : nodeDbUpgradeHIstoryGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbupgradehistory.isActive
     *
     * @return the value of dbupgradehistory.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbupgradehistory.isActive
     *
     * @param isActive the value for dbupgradehistory.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}