package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class DocumentList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.docId
     *
     * @mbg.generated
     */
    private Long docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.platformfileExtID
     *
     * @mbg.generated
     */
    private Long platformfileExtID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.docTypeId
     *
     * @mbg.generated
     */
    private Long docTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.docGuid
     *
     * @mbg.generated
     */
    private String docGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.fileName
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.fileSize
     *
     * @mbg.generated
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.memorySeaLevelTime
     *
     * @mbg.generated
     */
    private Date memorySeaLevelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.memoryLiveTimeSec
     *
     * @mbg.generated
     */
    private Long memoryLiveTimeSec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.memoryHitTimes
     *
     * @mbg.generated
     */
    private Long memoryHitTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.memoryPerHitComeUpSeconds
     *
     * @mbg.generated
     */
    private Long memoryPerHitComeUpSeconds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.storageClusterType
     *
     * @mbg.generated
     */
    private Integer storageClusterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.uploadedByPlatformUserGuid
     *
     * @mbg.generated
     */
    private String uploadedByPlatformUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.lastModifiedByPlatformUserGuid
     *
     * @mbg.generated
     */
    private String lastModifiedByPlatformUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.deletedByPlatformUserGuid
     *
     * @mbg.generated
     */
    private String deletedByPlatformUserGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.clusterStorageStatus
     *
     * @mbg.generated
     */
    private Integer clusterStorageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.fileExtName
     *
     * @mbg.generated
     */
    private String fileExtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.viewerCacheFileName
     *
     * @mbg.generated
     */
    private String viewerCacheFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.viewerCacheTimeLength
     *
     * @mbg.generated
     */
    private Long viewerCacheTimeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.viewerCacheTime
     *
     * @mbg.generated
     */
    private Date viewerCacheTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentlist.filePath
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.docId
     *
     * @return the value of documentlist.docId
     *
     * @mbg.generated
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.docId
     *
     * @param docId the value for documentlist.docId
     *
     * @mbg.generated
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.platformfileExtID
     *
     * @return the value of documentlist.platformfileExtID
     *
     * @mbg.generated
     */
    public Long getPlatformfileExtID() {
        return platformfileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.platformfileExtID
     *
     * @param platformfileExtID the value for documentlist.platformfileExtID
     *
     * @mbg.generated
     */
    public void setPlatformfileExtID(Long platformfileExtID) {
        this.platformfileExtID = platformfileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.docTypeId
     *
     * @return the value of documentlist.docTypeId
     *
     * @mbg.generated
     */
    public Long getDocTypeId() {
        return docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.docTypeId
     *
     * @param docTypeId the value for documentlist.docTypeId
     *
     * @mbg.generated
     */
    public void setDocTypeId(Long docTypeId) {
        this.docTypeId = docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.docGuid
     *
     * @return the value of documentlist.docGuid
     *
     * @mbg.generated
     */
    public String getDocGuid() {
        return docGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.docGuid
     *
     * @param docGuid the value for documentlist.docGuid
     *
     * @mbg.generated
     */
    public void setDocGuid(String docGuid) {
        this.docGuid = docGuid == null ? null : docGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.fileName
     *
     * @return the value of documentlist.fileName
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.fileName
     *
     * @param fileName the value for documentlist.fileName
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.fileSize
     *
     * @return the value of documentlist.fileSize
     *
     * @mbg.generated
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.fileSize
     *
     * @param fileSize the value for documentlist.fileSize
     *
     * @mbg.generated
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.version
     *
     * @return the value of documentlist.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.version
     *
     * @param version the value for documentlist.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.isActive
     *
     * @return the value of documentlist.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.isActive
     *
     * @param isActive the value for documentlist.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.createTime
     *
     * @return the value of documentlist.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.createTime
     *
     * @param createTime the value for documentlist.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.updateTime
     *
     * @return the value of documentlist.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.updateTime
     *
     * @param updateTime the value for documentlist.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.memorySeaLevelTime
     *
     * @return the value of documentlist.memorySeaLevelTime
     *
     * @mbg.generated
     */
    public Date getMemorySeaLevelTime() {
        return memorySeaLevelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.memorySeaLevelTime
     *
     * @param memorySeaLevelTime the value for documentlist.memorySeaLevelTime
     *
     * @mbg.generated
     */
    public void setMemorySeaLevelTime(Date memorySeaLevelTime) {
        this.memorySeaLevelTime = memorySeaLevelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.memoryLiveTimeSec
     *
     * @return the value of documentlist.memoryLiveTimeSec
     *
     * @mbg.generated
     */
    public Long getMemoryLiveTimeSec() {
        return memoryLiveTimeSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.memoryLiveTimeSec
     *
     * @param memoryLiveTimeSec the value for documentlist.memoryLiveTimeSec
     *
     * @mbg.generated
     */
    public void setMemoryLiveTimeSec(Long memoryLiveTimeSec) {
        this.memoryLiveTimeSec = memoryLiveTimeSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.memoryHitTimes
     *
     * @return the value of documentlist.memoryHitTimes
     *
     * @mbg.generated
     */
    public Long getMemoryHitTimes() {
        return memoryHitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.memoryHitTimes
     *
     * @param memoryHitTimes the value for documentlist.memoryHitTimes
     *
     * @mbg.generated
     */
    public void setMemoryHitTimes(Long memoryHitTimes) {
        this.memoryHitTimes = memoryHitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.memoryPerHitComeUpSeconds
     *
     * @return the value of documentlist.memoryPerHitComeUpSeconds
     *
     * @mbg.generated
     */
    public Long getMemoryPerHitComeUpSeconds() {
        return memoryPerHitComeUpSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.memoryPerHitComeUpSeconds
     *
     * @param memoryPerHitComeUpSeconds the value for documentlist.memoryPerHitComeUpSeconds
     *
     * @mbg.generated
     */
    public void setMemoryPerHitComeUpSeconds(Long memoryPerHitComeUpSeconds) {
        this.memoryPerHitComeUpSeconds = memoryPerHitComeUpSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.storageClusterType
     *
     * @return the value of documentlist.storageClusterType
     *
     * @mbg.generated
     */
    public Integer getStorageClusterType() {
        return storageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.storageClusterType
     *
     * @param storageClusterType the value for documentlist.storageClusterType
     *
     * @mbg.generated
     */
    public void setStorageClusterType(Integer storageClusterType) {
        this.storageClusterType = storageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.uploadedByPlatformUserGuid
     *
     * @return the value of documentlist.uploadedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public String getUploadedByPlatformUserGuid() {
        return uploadedByPlatformUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.uploadedByPlatformUserGuid
     *
     * @param uploadedByPlatformUserGuid the value for documentlist.uploadedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public void setUploadedByPlatformUserGuid(String uploadedByPlatformUserGuid) {
        this.uploadedByPlatformUserGuid = uploadedByPlatformUserGuid == null ? null : uploadedByPlatformUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.lastModifiedByPlatformUserGuid
     *
     * @return the value of documentlist.lastModifiedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public String getLastModifiedByPlatformUserGuid() {
        return lastModifiedByPlatformUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.lastModifiedByPlatformUserGuid
     *
     * @param lastModifiedByPlatformUserGuid the value for documentlist.lastModifiedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public void setLastModifiedByPlatformUserGuid(String lastModifiedByPlatformUserGuid) {
        this.lastModifiedByPlatformUserGuid = lastModifiedByPlatformUserGuid == null ? null : lastModifiedByPlatformUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.deletedByPlatformUserGuid
     *
     * @return the value of documentlist.deletedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public String getDeletedByPlatformUserGuid() {
        return deletedByPlatformUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.deletedByPlatformUserGuid
     *
     * @param deletedByPlatformUserGuid the value for documentlist.deletedByPlatformUserGuid
     *
     * @mbg.generated
     */
    public void setDeletedByPlatformUserGuid(String deletedByPlatformUserGuid) {
        this.deletedByPlatformUserGuid = deletedByPlatformUserGuid == null ? null : deletedByPlatformUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.clusterStorageStatus
     *
     * @return the value of documentlist.clusterStorageStatus
     *
     * @mbg.generated
     */
    public Integer getClusterStorageStatus() {
        return clusterStorageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.clusterStorageStatus
     *
     * @param clusterStorageStatus the value for documentlist.clusterStorageStatus
     *
     * @mbg.generated
     */
    public void setClusterStorageStatus(Integer clusterStorageStatus) {
        this.clusterStorageStatus = clusterStorageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.fileExtName
     *
     * @return the value of documentlist.fileExtName
     *
     * @mbg.generated
     */
    public String getFileExtName() {
        return fileExtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.fileExtName
     *
     * @param fileExtName the value for documentlist.fileExtName
     *
     * @mbg.generated
     */
    public void setFileExtName(String fileExtName) {
        this.fileExtName = fileExtName == null ? null : fileExtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.viewerCacheFileName
     *
     * @return the value of documentlist.viewerCacheFileName
     *
     * @mbg.generated
     */
    public String getViewerCacheFileName() {
        return viewerCacheFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.viewerCacheFileName
     *
     * @param viewerCacheFileName the value for documentlist.viewerCacheFileName
     *
     * @mbg.generated
     */
    public void setViewerCacheFileName(String viewerCacheFileName) {
        this.viewerCacheFileName = viewerCacheFileName == null ? null : viewerCacheFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.viewerCacheTimeLength
     *
     * @return the value of documentlist.viewerCacheTimeLength
     *
     * @mbg.generated
     */
    public Long getViewerCacheTimeLength() {
        return viewerCacheTimeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.viewerCacheTimeLength
     *
     * @param viewerCacheTimeLength the value for documentlist.viewerCacheTimeLength
     *
     * @mbg.generated
     */
    public void setViewerCacheTimeLength(Long viewerCacheTimeLength) {
        this.viewerCacheTimeLength = viewerCacheTimeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.viewerCacheTime
     *
     * @return the value of documentlist.viewerCacheTime
     *
     * @mbg.generated
     */
    public Date getViewerCacheTime() {
        return viewerCacheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.viewerCacheTime
     *
     * @param viewerCacheTime the value for documentlist.viewerCacheTime
     *
     * @mbg.generated
     */
    public void setViewerCacheTime(Date viewerCacheTime) {
        this.viewerCacheTime = viewerCacheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentlist.filePath
     *
     * @return the value of documentlist.filePath
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentlist.filePath
     *
     * @param filePath the value for documentlist.filePath
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}