package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class OperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.operationLogId
     *
     * @mbg.generated
     */
    private Long operationLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.operationStorageClusterType
     *
     * @mbg.generated
     */
    private Integer operationStorageClusterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.operationLogGuid
     *
     * @mbg.generated
     */
    private String operationLogGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.userId
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.operationType
     *
     * @mbg.generated
     */
    private Integer operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.operationLogTime
     *
     * @mbg.generated
     */
    private Date operationLogTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.appId
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.docId
     *
     * @mbg.generated
     */
    private Long docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.exfModuleId
     *
     * @mbg.generated
     */
    private Long exfModuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.viewId
     *
     * @mbg.generated
     */
    private Long viewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.platformControllerId
     *
     * @mbg.generated
     */
    private Long platformControllerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.platformActionId
     *
     * @mbg.generated
     */
    private Long platformActionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.usingObjectId
     *
     * @mbg.generated
     */
    private Long usingObjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.bizUserRoleId
     *
     * @mbg.generated
     */
    private Long bizUserRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.deviceId
     *
     * @mbg.generated
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.devLangId
     *
     * @mbg.generated
     */
    private Long devLangId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.workFlowStatusId
     *
     * @mbg.generated
     */
    private Long workFlowStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.isDocExistingCurrently
     *
     * @mbg.generated
     */
    private Boolean isDocExistingCurrently;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.userGuid
     *
     * @mbg.generated
     */
    private String userGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.appGuid
     *
     * @mbg.generated
     */
    private String appGuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.operationLogId
     *
     * @return the value of operationlog.operationLogId
     *
     * @mbg.generated
     */
    public Long getOperationLogId() {
        return operationLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.operationLogId
     *
     * @param operationLogId the value for operationlog.operationLogId
     *
     * @mbg.generated
     */
    public void setOperationLogId(Long operationLogId) {
        this.operationLogId = operationLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.operationStorageClusterType
     *
     * @return the value of operationlog.operationStorageClusterType
     *
     * @mbg.generated
     */
    public Integer getOperationStorageClusterType() {
        return operationStorageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.operationStorageClusterType
     *
     * @param operationStorageClusterType the value for operationlog.operationStorageClusterType
     *
     * @mbg.generated
     */
    public void setOperationStorageClusterType(Integer operationStorageClusterType) {
        this.operationStorageClusterType = operationStorageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.operationLogGuid
     *
     * @return the value of operationlog.operationLogGuid
     *
     * @mbg.generated
     */
    public String getOperationLogGuid() {
        return operationLogGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.operationLogGuid
     *
     * @param operationLogGuid the value for operationlog.operationLogGuid
     *
     * @mbg.generated
     */
    public void setOperationLogGuid(String operationLogGuid) {
        this.operationLogGuid = operationLogGuid == null ? null : operationLogGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.userId
     *
     * @return the value of operationlog.userId
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.userId
     *
     * @param userId the value for operationlog.userId
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.userName
     *
     * @return the value of operationlog.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.userName
     *
     * @param userName the value for operationlog.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.operationType
     *
     * @return the value of operationlog.operationType
     *
     * @mbg.generated
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.operationType
     *
     * @param operationType the value for operationlog.operationType
     *
     * @mbg.generated
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.operationLogTime
     *
     * @return the value of operationlog.operationLogTime
     *
     * @mbg.generated
     */
    public Date getOperationLogTime() {
        return operationLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.operationLogTime
     *
     * @param operationLogTime the value for operationlog.operationLogTime
     *
     * @mbg.generated
     */
    public void setOperationLogTime(Date operationLogTime) {
        this.operationLogTime = operationLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.appId
     *
     * @return the value of operationlog.appId
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.appId
     *
     * @param appId the value for operationlog.appId
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.docId
     *
     * @return the value of operationlog.docId
     *
     * @mbg.generated
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.docId
     *
     * @param docId the value for operationlog.docId
     *
     * @mbg.generated
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.exfModuleId
     *
     * @return the value of operationlog.exfModuleId
     *
     * @mbg.generated
     */
    public Long getExfModuleId() {
        return exfModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.exfModuleId
     *
     * @param exfModuleId the value for operationlog.exfModuleId
     *
     * @mbg.generated
     */
    public void setExfModuleId(Long exfModuleId) {
        this.exfModuleId = exfModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.viewId
     *
     * @return the value of operationlog.viewId
     *
     * @mbg.generated
     */
    public Long getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.viewId
     *
     * @param viewId the value for operationlog.viewId
     *
     * @mbg.generated
     */
    public void setViewId(Long viewId) {
        this.viewId = viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.platformControllerId
     *
     * @return the value of operationlog.platformControllerId
     *
     * @mbg.generated
     */
    public Long getPlatformControllerId() {
        return platformControllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.platformControllerId
     *
     * @param platformControllerId the value for operationlog.platformControllerId
     *
     * @mbg.generated
     */
    public void setPlatformControllerId(Long platformControllerId) {
        this.platformControllerId = platformControllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.platformActionId
     *
     * @return the value of operationlog.platformActionId
     *
     * @mbg.generated
     */
    public Long getPlatformActionId() {
        return platformActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.platformActionId
     *
     * @param platformActionId the value for operationlog.platformActionId
     *
     * @mbg.generated
     */
    public void setPlatformActionId(Long platformActionId) {
        this.platformActionId = platformActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.usingObjectId
     *
     * @return the value of operationlog.usingObjectId
     *
     * @mbg.generated
     */
    public Long getUsingObjectId() {
        return usingObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.usingObjectId
     *
     * @param usingObjectId the value for operationlog.usingObjectId
     *
     * @mbg.generated
     */
    public void setUsingObjectId(Long usingObjectId) {
        this.usingObjectId = usingObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.bizUserRoleId
     *
     * @return the value of operationlog.bizUserRoleId
     *
     * @mbg.generated
     */
    public Long getBizUserRoleId() {
        return bizUserRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.bizUserRoleId
     *
     * @param bizUserRoleId the value for operationlog.bizUserRoleId
     *
     * @mbg.generated
     */
    public void setBizUserRoleId(Long bizUserRoleId) {
        this.bizUserRoleId = bizUserRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.deviceId
     *
     * @return the value of operationlog.deviceId
     *
     * @mbg.generated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.deviceId
     *
     * @param deviceId the value for operationlog.deviceId
     *
     * @mbg.generated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.devLangId
     *
     * @return the value of operationlog.devLangId
     *
     * @mbg.generated
     */
    public Long getDevLangId() {
        return devLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.devLangId
     *
     * @param devLangId the value for operationlog.devLangId
     *
     * @mbg.generated
     */
    public void setDevLangId(Long devLangId) {
        this.devLangId = devLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.workFlowStatusId
     *
     * @return the value of operationlog.workFlowStatusId
     *
     * @mbg.generated
     */
    public Long getWorkFlowStatusId() {
        return workFlowStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.workFlowStatusId
     *
     * @param workFlowStatusId the value for operationlog.workFlowStatusId
     *
     * @mbg.generated
     */
    public void setWorkFlowStatusId(Long workFlowStatusId) {
        this.workFlowStatusId = workFlowStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.isDocExistingCurrently
     *
     * @return the value of operationlog.isDocExistingCurrently
     *
     * @mbg.generated
     */
    public Boolean getIsDocExistingCurrently() {
        return isDocExistingCurrently;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.isDocExistingCurrently
     *
     * @param isDocExistingCurrently the value for operationlog.isDocExistingCurrently
     *
     * @mbg.generated
     */
    public void setIsDocExistingCurrently(Boolean isDocExistingCurrently) {
        this.isDocExistingCurrently = isDocExistingCurrently;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.isActive
     *
     * @return the value of operationlog.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.isActive
     *
     * @param isActive the value for operationlog.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.userGuid
     *
     * @return the value of operationlog.userGuid
     *
     * @mbg.generated
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.userGuid
     *
     * @param userGuid the value for operationlog.userGuid
     *
     * @mbg.generated
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationlog.appGuid
     *
     * @return the value of operationlog.appGuid
     *
     * @mbg.generated
     */
    public String getAppGuid() {
        return appGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationlog.appGuid
     *
     * @param appGuid the value for operationlog.appGuid
     *
     * @mbg.generated
     */
    public void setAppGuid(String appGuid) {
        this.appGuid = appGuid == null ? null : appGuid.trim();
    }
}