package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class PlatformDocTypeFileExtRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.docTypeFileExtRelationID
     *
     * @mbg.generated
     */
    private Long docTypeFileExtRelationID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.docTypeFileExtRelationGuid
     *
     * @mbg.generated
     */
    private String docTypeFileExtRelationGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.docTypeId
     *
     * @mbg.generated
     */
    private Long docTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.platformFileExtID
     *
     * @mbg.generated
     */
    private Long platformFileExtID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.isBoardCast
     *
     * @mbg.generated
     */
    private Boolean isBoardCast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctypefileextrelation.boardCastCount
     *
     * @mbg.generated
     */
    private Long boardCastCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.docTypeFileExtRelationID
     *
     * @return the value of platformdoctypefileextrelation.docTypeFileExtRelationID
     *
     * @mbg.generated
     */
    public Long getDocTypeFileExtRelationID() {
        return docTypeFileExtRelationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.docTypeFileExtRelationID
     *
     * @param docTypeFileExtRelationID the value for platformdoctypefileextrelation.docTypeFileExtRelationID
     *
     * @mbg.generated
     */
    public void setDocTypeFileExtRelationID(Long docTypeFileExtRelationID) {
        this.docTypeFileExtRelationID = docTypeFileExtRelationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.docTypeFileExtRelationGuid
     *
     * @return the value of platformdoctypefileextrelation.docTypeFileExtRelationGuid
     *
     * @mbg.generated
     */
    public String getDocTypeFileExtRelationGuid() {
        return docTypeFileExtRelationGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.docTypeFileExtRelationGuid
     *
     * @param docTypeFileExtRelationGuid the value for platformdoctypefileextrelation.docTypeFileExtRelationGuid
     *
     * @mbg.generated
     */
    public void setDocTypeFileExtRelationGuid(String docTypeFileExtRelationGuid) {
        this.docTypeFileExtRelationGuid = docTypeFileExtRelationGuid == null ? null : docTypeFileExtRelationGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.docTypeId
     *
     * @return the value of platformdoctypefileextrelation.docTypeId
     *
     * @mbg.generated
     */
    public Long getDocTypeId() {
        return docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.docTypeId
     *
     * @param docTypeId the value for platformdoctypefileextrelation.docTypeId
     *
     * @mbg.generated
     */
    public void setDocTypeId(Long docTypeId) {
        this.docTypeId = docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.platformFileExtID
     *
     * @return the value of platformdoctypefileextrelation.platformFileExtID
     *
     * @mbg.generated
     */
    public Long getPlatformFileExtID() {
        return platformFileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.platformFileExtID
     *
     * @param platformFileExtID the value for platformdoctypefileextrelation.platformFileExtID
     *
     * @mbg.generated
     */
    public void setPlatformFileExtID(Long platformFileExtID) {
        this.platformFileExtID = platformFileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.isActive
     *
     * @return the value of platformdoctypefileextrelation.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.isActive
     *
     * @param isActive the value for platformdoctypefileextrelation.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.createTime
     *
     * @return the value of platformdoctypefileextrelation.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.createTime
     *
     * @param createTime the value for platformdoctypefileextrelation.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.updateTime
     *
     * @return the value of platformdoctypefileextrelation.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.updateTime
     *
     * @param updateTime the value for platformdoctypefileextrelation.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.isBoardCast
     *
     * @return the value of platformdoctypefileextrelation.isBoardCast
     *
     * @mbg.generated
     */
    public Boolean getIsBoardCast() {
        return isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.isBoardCast
     *
     * @param isBoardCast the value for platformdoctypefileextrelation.isBoardCast
     *
     * @mbg.generated
     */
    public void setIsBoardCast(Boolean isBoardCast) {
        this.isBoardCast = isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctypefileextrelation.boardCastCount
     *
     * @return the value of platformdoctypefileextrelation.boardCastCount
     *
     * @mbg.generated
     */
    public Long getBoardCastCount() {
        return boardCastCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctypefileextrelation.boardCastCount
     *
     * @param boardCastCount the value for platformdoctypefileextrelation.boardCastCount
     *
     * @mbg.generated
     */
    public void setBoardCastCount(Long boardCastCount) {
        this.boardCastCount = boardCastCount;
    }
}