package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class PlatformDocType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.docTypeId
     *
     * @mbg.generated
     */
    private Long docTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.docTypeGuid
     *
     * @mbg.generated
     */
    private String docTypeGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.docTypeName
     *
     * @mbg.generated
     */
    private String docTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.docTypeDesc
     *
     * @mbg.generated
     */
    private String docTypeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.maxFileSize
     *
     * @mbg.generated
     */
    private Integer maxFileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.fileShareFolder
     *
     * @mbg.generated
     */
    private String fileShareFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformdoctype.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.docTypeId
     *
     * @return the value of platformdoctype.docTypeId
     *
     * @mbg.generated
     */
    public Long getDocTypeId() {
        return docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.docTypeId
     *
     * @param docTypeId the value for platformdoctype.docTypeId
     *
     * @mbg.generated
     */
    public void setDocTypeId(Long docTypeId) {
        this.docTypeId = docTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.docTypeGuid
     *
     * @return the value of platformdoctype.docTypeGuid
     *
     * @mbg.generated
     */
    public String getDocTypeGuid() {
        return docTypeGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.docTypeGuid
     *
     * @param docTypeGuid the value for platformdoctype.docTypeGuid
     *
     * @mbg.generated
     */
    public void setDocTypeGuid(String docTypeGuid) {
        this.docTypeGuid = docTypeGuid == null ? null : docTypeGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.docTypeName
     *
     * @return the value of platformdoctype.docTypeName
     *
     * @mbg.generated
     */
    public String getDocTypeName() {
        return docTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.docTypeName
     *
     * @param docTypeName the value for platformdoctype.docTypeName
     *
     * @mbg.generated
     */
    public void setDocTypeName(String docTypeName) {
        this.docTypeName = docTypeName == null ? null : docTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.docTypeDesc
     *
     * @return the value of platformdoctype.docTypeDesc
     *
     * @mbg.generated
     */
    public String getDocTypeDesc() {
        return docTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.docTypeDesc
     *
     * @param docTypeDesc the value for platformdoctype.docTypeDesc
     *
     * @mbg.generated
     */
    public void setDocTypeDesc(String docTypeDesc) {
        this.docTypeDesc = docTypeDesc == null ? null : docTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.maxFileSize
     *
     * @return the value of platformdoctype.maxFileSize
     *
     * @mbg.generated
     */
    public Integer getMaxFileSize() {
        return maxFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.maxFileSize
     *
     * @param maxFileSize the value for platformdoctype.maxFileSize
     *
     * @mbg.generated
     */
    public void setMaxFileSize(Integer maxFileSize) {
        this.maxFileSize = maxFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.fileShareFolder
     *
     * @return the value of platformdoctype.fileShareFolder
     *
     * @mbg.generated
     */
    public String getFileShareFolder() {
        return fileShareFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.fileShareFolder
     *
     * @param fileShareFolder the value for platformdoctype.fileShareFolder
     *
     * @mbg.generated
     */
    public void setFileShareFolder(String fileShareFolder) {
        this.fileShareFolder = fileShareFolder == null ? null : fileShareFolder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.comment
     *
     * @return the value of platformdoctype.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.comment
     *
     * @param comment the value for platformdoctype.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.isActive
     *
     * @return the value of platformdoctype.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.isActive
     *
     * @param isActive the value for platformdoctype.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.createTime
     *
     * @return the value of platformdoctype.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.createTime
     *
     * @param createTime the value for platformdoctype.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformdoctype.updateTime
     *
     * @return the value of platformdoctype.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformdoctype.updateTime
     *
     * @param updateTime the value for platformdoctype.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}