package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class PlatformFileExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.fileExtID
     *
     * @mbg.generated
     */
    private Long fileExtID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.fileExtGuid
     *
     * @mbg.generated
     */
    private String fileExtGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.fileExtName
     *
     * @mbg.generated
     */
    private String fileExtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.isBoardCast
     *
     * @mbg.generated
     */
    private Boolean isBoardCast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformfileext.boardCastCount
     *
     * @mbg.generated
     */
    private Long boardCastCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.fileExtID
     *
     * @return the value of platformfileext.fileExtID
     *
     * @mbg.generated
     */
    public Long getFileExtID() {
        return fileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.fileExtID
     *
     * @param fileExtID the value for platformfileext.fileExtID
     *
     * @mbg.generated
     */
    public void setFileExtID(Long fileExtID) {
        this.fileExtID = fileExtID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.fileExtGuid
     *
     * @return the value of platformfileext.fileExtGuid
     *
     * @mbg.generated
     */
    public String getFileExtGuid() {
        return fileExtGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.fileExtGuid
     *
     * @param fileExtGuid the value for platformfileext.fileExtGuid
     *
     * @mbg.generated
     */
    public void setFileExtGuid(String fileExtGuid) {
        this.fileExtGuid = fileExtGuid == null ? null : fileExtGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.fileExtName
     *
     * @return the value of platformfileext.fileExtName
     *
     * @mbg.generated
     */
    public String getFileExtName() {
        return fileExtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.fileExtName
     *
     * @param fileExtName the value for platformfileext.fileExtName
     *
     * @mbg.generated
     */
    public void setFileExtName(String fileExtName) {
        this.fileExtName = fileExtName == null ? null : fileExtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.createTime
     *
     * @return the value of platformfileext.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.createTime
     *
     * @param createTime the value for platformfileext.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.updateTime
     *
     * @return the value of platformfileext.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.updateTime
     *
     * @param updateTime the value for platformfileext.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.isActive
     *
     * @return the value of platformfileext.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.isActive
     *
     * @param isActive the value for platformfileext.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.isBoardCast
     *
     * @return the value of platformfileext.isBoardCast
     *
     * @mbg.generated
     */
    public Boolean getIsBoardCast() {
        return isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.isBoardCast
     *
     * @param isBoardCast the value for platformfileext.isBoardCast
     *
     * @mbg.generated
     */
    public void setIsBoardCast(Boolean isBoardCast) {
        this.isBoardCast = isBoardCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformfileext.boardCastCount
     *
     * @return the value of platformfileext.boardCastCount
     *
     * @mbg.generated
     */
    public Long getBoardCastCount() {
        return boardCastCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformfileext.boardCastCount
     *
     * @param boardCastCount the value for platformfileext.boardCastCount
     *
     * @mbg.generated
     */
    public void setBoardCastCount(Long boardCastCount) {
        this.boardCastCount = boardCastCount;
    }
}