package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class RequestLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.reqId
     *
     * @mbg.generated
     */
    private Long reqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.appId
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.appName
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.appGuid
     *
     * @mbg.generated
     */
    private String appGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.userId
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.reqStorageClusterType
     *
     * @mbg.generated
     */
    private Integer reqStorageClusterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.reqGuid
     *
     * @mbg.generated
     */
    private String reqGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.userGuid
     *
     * @mbg.generated
     */
    private String userGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestlog.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.reqId
     *
     * @return the value of requestlog.reqId
     *
     * @mbg.generated
     */
    public Long getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.reqId
     *
     * @param reqId the value for requestlog.reqId
     *
     * @mbg.generated
     */
    public void setReqId(Long reqId) {
        this.reqId = reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.appId
     *
     * @return the value of requestlog.appId
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.appId
     *
     * @param appId the value for requestlog.appId
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.appName
     *
     * @return the value of requestlog.appName
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.appName
     *
     * @param appName the value for requestlog.appName
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.appGuid
     *
     * @return the value of requestlog.appGuid
     *
     * @mbg.generated
     */
    public String getAppGuid() {
        return appGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.appGuid
     *
     * @param appGuid the value for requestlog.appGuid
     *
     * @mbg.generated
     */
    public void setAppGuid(String appGuid) {
        this.appGuid = appGuid == null ? null : appGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.userId
     *
     * @return the value of requestlog.userId
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.userId
     *
     * @param userId the value for requestlog.userId
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.createTime
     *
     * @return the value of requestlog.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.createTime
     *
     * @param createTime the value for requestlog.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.reqStorageClusterType
     *
     * @return the value of requestlog.reqStorageClusterType
     *
     * @mbg.generated
     */
    public Integer getReqStorageClusterType() {
        return reqStorageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.reqStorageClusterType
     *
     * @param reqStorageClusterType the value for requestlog.reqStorageClusterType
     *
     * @mbg.generated
     */
    public void setReqStorageClusterType(Integer reqStorageClusterType) {
        this.reqStorageClusterType = reqStorageClusterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.reqGuid
     *
     * @return the value of requestlog.reqGuid
     *
     * @mbg.generated
     */
    public String getReqGuid() {
        return reqGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.reqGuid
     *
     * @param reqGuid the value for requestlog.reqGuid
     *
     * @mbg.generated
     */
    public void setReqGuid(String reqGuid) {
        this.reqGuid = reqGuid == null ? null : reqGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.isActive
     *
     * @return the value of requestlog.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.isActive
     *
     * @param isActive the value for requestlog.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.userGuid
     *
     * @return the value of requestlog.userGuid
     *
     * @mbg.generated
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.userGuid
     *
     * @param userGuid the value for requestlog.userGuid
     *
     * @mbg.generated
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestlog.url
     *
     * @return the value of requestlog.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestlog.url
     *
     * @param url the value for requestlog.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}