package cn.Boy.DiskFile.pojo;

import java.util.Date;

public class UnitNodeRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeRelationId
     *
     * @mbg.generated
     */
    private Long unitNodeRelationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.r_crystalNodeId
     *
     * @mbg.generated
     */
    private Long r_crystalNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.appId
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.r_crystalNodeGuid
     *
     * @mbg.generated
     */
    private String r_crystalNodeGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.isActive
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeRelationGuid
     *
     * @mbg.generated
     */
    private String unitNodeRelationGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeRole
     *
     * @mbg.generated
     */
    private Long unitNodeRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeSource
     *
     * @mbg.generated
     */
    private Integer unitNodeSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeIp
     *
     * @mbg.generated
     */
    private String unitNodeIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodePort
     *
     * @mbg.generated
     */
    private Long unitNodePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.unitNodeProtocolType
     *
     * @mbg.generated
     */
    private Integer unitNodeProtocolType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.mem_totalHeap
     *
     * @mbg.generated
     */
    private Double mem_totalHeap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.mem_heapUsed
     *
     * @mbg.generated
     */
    private Double mem_heapUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.mem_totalForCurrentProcess
     *
     * @mbg.generated
     */
    private Double mem_totalForCurrentProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.mem_totalOnV8EngineUsing
     *
     * @mbg.generated
     */
    private Double mem_totalOnV8EngineUsing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.mem_usedMemRate
     *
     * @mbg.generated
     */
    private Double mem_usedMemRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.cpuArch
     *
     * @mbg.generated
     */
    private String cpuArch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.cpuInfo
     *
     * @mbg.generated
     */
    private String cpuInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.freemem
     *
     * @mbg.generated
     */
    private Long freemem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.hostName
     *
     * @mbg.generated
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.loadAvg
     *
     * @mbg.generated
     */
    private String loadAvg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.networkInterface
     *
     * @mbg.generated
     */
    private String networkInterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.platformtype
     *
     * @mbg.generated
     */
    private String platformtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.platformVersion
     *
     * @mbg.generated
     */
    private String platformVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.osTempDir
     *
     * @mbg.generated
     */
    private String osTempDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.totalMemory
     *
     * @mbg.generated
     */
    private Long totalMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.osType
     *
     * @mbg.generated
     */
    private String osType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitnoderelation.nodeNormalRunedTime
     *
     * @mbg.generated
     */
    private Long nodeNormalRunedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeRelationId
     *
     * @return the value of unitnoderelation.unitNodeRelationId
     *
     * @mbg.generated
     */
    public Long getUnitNodeRelationId() {
        return unitNodeRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeRelationId
     *
     * @param unitNodeRelationId the value for unitnoderelation.unitNodeRelationId
     *
     * @mbg.generated
     */
    public void setUnitNodeRelationId(Long unitNodeRelationId) {
        this.unitNodeRelationId = unitNodeRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.r_crystalNodeId
     *
     * @return the value of unitnoderelation.r_crystalNodeId
     *
     * @mbg.generated
     */
    public Long getR_crystalNodeId() {
        return r_crystalNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.r_crystalNodeId
     *
     * @param r_crystalNodeId the value for unitnoderelation.r_crystalNodeId
     *
     * @mbg.generated
     */
    public void setR_crystalNodeId(Long r_crystalNodeId) {
        this.r_crystalNodeId = r_crystalNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.appId
     *
     * @return the value of unitnoderelation.appId
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.appId
     *
     * @param appId the value for unitnoderelation.appId
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.r_crystalNodeGuid
     *
     * @return the value of unitnoderelation.r_crystalNodeGuid
     *
     * @mbg.generated
     */
    public String getR_crystalNodeGuid() {
        return r_crystalNodeGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.r_crystalNodeGuid
     *
     * @param r_crystalNodeGuid the value for unitnoderelation.r_crystalNodeGuid
     *
     * @mbg.generated
     */
    public void setR_crystalNodeGuid(String r_crystalNodeGuid) {
        this.r_crystalNodeGuid = r_crystalNodeGuid == null ? null : r_crystalNodeGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.isActive
     *
     * @return the value of unitnoderelation.isActive
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.isActive
     *
     * @param isActive the value for unitnoderelation.isActive
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.createTime
     *
     * @return the value of unitnoderelation.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.createTime
     *
     * @param createTime the value for unitnoderelation.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.updateTime
     *
     * @return the value of unitnoderelation.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.updateTime
     *
     * @param updateTime the value for unitnoderelation.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeRelationGuid
     *
     * @return the value of unitnoderelation.unitNodeRelationGuid
     *
     * @mbg.generated
     */
    public String getUnitNodeRelationGuid() {
        return unitNodeRelationGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeRelationGuid
     *
     * @param unitNodeRelationGuid the value for unitnoderelation.unitNodeRelationGuid
     *
     * @mbg.generated
     */
    public void setUnitNodeRelationGuid(String unitNodeRelationGuid) {
        this.unitNodeRelationGuid = unitNodeRelationGuid == null ? null : unitNodeRelationGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeRole
     *
     * @return the value of unitnoderelation.unitNodeRole
     *
     * @mbg.generated
     */
    public Long getUnitNodeRole() {
        return unitNodeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeRole
     *
     * @param unitNodeRole the value for unitnoderelation.unitNodeRole
     *
     * @mbg.generated
     */
    public void setUnitNodeRole(Long unitNodeRole) {
        this.unitNodeRole = unitNodeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeSource
     *
     * @return the value of unitnoderelation.unitNodeSource
     *
     * @mbg.generated
     */
    public Integer getUnitNodeSource() {
        return unitNodeSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeSource
     *
     * @param unitNodeSource the value for unitnoderelation.unitNodeSource
     *
     * @mbg.generated
     */
    public void setUnitNodeSource(Integer unitNodeSource) {
        this.unitNodeSource = unitNodeSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeIp
     *
     * @return the value of unitnoderelation.unitNodeIp
     *
     * @mbg.generated
     */
    public String getUnitNodeIp() {
        return unitNodeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeIp
     *
     * @param unitNodeIp the value for unitnoderelation.unitNodeIp
     *
     * @mbg.generated
     */
    public void setUnitNodeIp(String unitNodeIp) {
        this.unitNodeIp = unitNodeIp == null ? null : unitNodeIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodePort
     *
     * @return the value of unitnoderelation.unitNodePort
     *
     * @mbg.generated
     */
    public Long getUnitNodePort() {
        return unitNodePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodePort
     *
     * @param unitNodePort the value for unitnoderelation.unitNodePort
     *
     * @mbg.generated
     */
    public void setUnitNodePort(Long unitNodePort) {
        this.unitNodePort = unitNodePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.unitNodeProtocolType
     *
     * @return the value of unitnoderelation.unitNodeProtocolType
     *
     * @mbg.generated
     */
    public Integer getUnitNodeProtocolType() {
        return unitNodeProtocolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.unitNodeProtocolType
     *
     * @param unitNodeProtocolType the value for unitnoderelation.unitNodeProtocolType
     *
     * @mbg.generated
     */
    public void setUnitNodeProtocolType(Integer unitNodeProtocolType) {
        this.unitNodeProtocolType = unitNodeProtocolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.mem_totalHeap
     *
     * @return the value of unitnoderelation.mem_totalHeap
     *
     * @mbg.generated
     */
    public Double getMem_totalHeap() {
        return mem_totalHeap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.mem_totalHeap
     *
     * @param mem_totalHeap the value for unitnoderelation.mem_totalHeap
     *
     * @mbg.generated
     */
    public void setMem_totalHeap(Double mem_totalHeap) {
        this.mem_totalHeap = mem_totalHeap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.mem_heapUsed
     *
     * @return the value of unitnoderelation.mem_heapUsed
     *
     * @mbg.generated
     */
    public Double getMem_heapUsed() {
        return mem_heapUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.mem_heapUsed
     *
     * @param mem_heapUsed the value for unitnoderelation.mem_heapUsed
     *
     * @mbg.generated
     */
    public void setMem_heapUsed(Double mem_heapUsed) {
        this.mem_heapUsed = mem_heapUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.mem_totalForCurrentProcess
     *
     * @return the value of unitnoderelation.mem_totalForCurrentProcess
     *
     * @mbg.generated
     */
    public Double getMem_totalForCurrentProcess() {
        return mem_totalForCurrentProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.mem_totalForCurrentProcess
     *
     * @param mem_totalForCurrentProcess the value for unitnoderelation.mem_totalForCurrentProcess
     *
     * @mbg.generated
     */
    public void setMem_totalForCurrentProcess(Double mem_totalForCurrentProcess) {
        this.mem_totalForCurrentProcess = mem_totalForCurrentProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.mem_totalOnV8EngineUsing
     *
     * @return the value of unitnoderelation.mem_totalOnV8EngineUsing
     *
     * @mbg.generated
     */
    public Double getMem_totalOnV8EngineUsing() {
        return mem_totalOnV8EngineUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.mem_totalOnV8EngineUsing
     *
     * @param mem_totalOnV8EngineUsing the value for unitnoderelation.mem_totalOnV8EngineUsing
     *
     * @mbg.generated
     */
    public void setMem_totalOnV8EngineUsing(Double mem_totalOnV8EngineUsing) {
        this.mem_totalOnV8EngineUsing = mem_totalOnV8EngineUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.mem_usedMemRate
     *
     * @return the value of unitnoderelation.mem_usedMemRate
     *
     * @mbg.generated
     */
    public Double getMem_usedMemRate() {
        return mem_usedMemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.mem_usedMemRate
     *
     * @param mem_usedMemRate the value for unitnoderelation.mem_usedMemRate
     *
     * @mbg.generated
     */
    public void setMem_usedMemRate(Double mem_usedMemRate) {
        this.mem_usedMemRate = mem_usedMemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.cpuArch
     *
     * @return the value of unitnoderelation.cpuArch
     *
     * @mbg.generated
     */
    public String getCpuArch() {
        return cpuArch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.cpuArch
     *
     * @param cpuArch the value for unitnoderelation.cpuArch
     *
     * @mbg.generated
     */
    public void setCpuArch(String cpuArch) {
        this.cpuArch = cpuArch == null ? null : cpuArch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.cpuInfo
     *
     * @return the value of unitnoderelation.cpuInfo
     *
     * @mbg.generated
     */
    public String getCpuInfo() {
        return cpuInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.cpuInfo
     *
     * @param cpuInfo the value for unitnoderelation.cpuInfo
     *
     * @mbg.generated
     */
    public void setCpuInfo(String cpuInfo) {
        this.cpuInfo = cpuInfo == null ? null : cpuInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.freemem
     *
     * @return the value of unitnoderelation.freemem
     *
     * @mbg.generated
     */
    public Long getFreemem() {
        return freemem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.freemem
     *
     * @param freemem the value for unitnoderelation.freemem
     *
     * @mbg.generated
     */
    public void setFreemem(Long freemem) {
        this.freemem = freemem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.hostName
     *
     * @return the value of unitnoderelation.hostName
     *
     * @mbg.generated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.hostName
     *
     * @param hostName the value for unitnoderelation.hostName
     *
     * @mbg.generated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.loadAvg
     *
     * @return the value of unitnoderelation.loadAvg
     *
     * @mbg.generated
     */
    public String getLoadAvg() {
        return loadAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.loadAvg
     *
     * @param loadAvg the value for unitnoderelation.loadAvg
     *
     * @mbg.generated
     */
    public void setLoadAvg(String loadAvg) {
        this.loadAvg = loadAvg == null ? null : loadAvg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.networkInterface
     *
     * @return the value of unitnoderelation.networkInterface
     *
     * @mbg.generated
     */
    public String getNetworkInterface() {
        return networkInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.networkInterface
     *
     * @param networkInterface the value for unitnoderelation.networkInterface
     *
     * @mbg.generated
     */
    public void setNetworkInterface(String networkInterface) {
        this.networkInterface = networkInterface == null ? null : networkInterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.platformtype
     *
     * @return the value of unitnoderelation.platformtype
     *
     * @mbg.generated
     */
    public String getPlatformtype() {
        return platformtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.platformtype
     *
     * @param platformtype the value for unitnoderelation.platformtype
     *
     * @mbg.generated
     */
    public void setPlatformtype(String platformtype) {
        this.platformtype = platformtype == null ? null : platformtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.platformVersion
     *
     * @return the value of unitnoderelation.platformVersion
     *
     * @mbg.generated
     */
    public String getPlatformVersion() {
        return platformVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.platformVersion
     *
     * @param platformVersion the value for unitnoderelation.platformVersion
     *
     * @mbg.generated
     */
    public void setPlatformVersion(String platformVersion) {
        this.platformVersion = platformVersion == null ? null : platformVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.osTempDir
     *
     * @return the value of unitnoderelation.osTempDir
     *
     * @mbg.generated
     */
    public String getOsTempDir() {
        return osTempDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.osTempDir
     *
     * @param osTempDir the value for unitnoderelation.osTempDir
     *
     * @mbg.generated
     */
    public void setOsTempDir(String osTempDir) {
        this.osTempDir = osTempDir == null ? null : osTempDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.totalMemory
     *
     * @return the value of unitnoderelation.totalMemory
     *
     * @mbg.generated
     */
    public Long getTotalMemory() {
        return totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.totalMemory
     *
     * @param totalMemory the value for unitnoderelation.totalMemory
     *
     * @mbg.generated
     */
    public void setTotalMemory(Long totalMemory) {
        this.totalMemory = totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.osType
     *
     * @return the value of unitnoderelation.osType
     *
     * @mbg.generated
     */
    public String getOsType() {
        return osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.osType
     *
     * @param osType the value for unitnoderelation.osType
     *
     * @mbg.generated
     */
    public void setOsType(String osType) {
        this.osType = osType == null ? null : osType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitnoderelation.nodeNormalRunedTime
     *
     * @return the value of unitnoderelation.nodeNormalRunedTime
     *
     * @mbg.generated
     */
    public Long getNodeNormalRunedTime() {
        return nodeNormalRunedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitnoderelation.nodeNormalRunedTime
     *
     * @param nodeNormalRunedTime the value for unitnoderelation.nodeNormalRunedTime
     *
     * @mbg.generated
     */
    public void setNodeNormalRunedTime(Long nodeNormalRunedTime) {
        this.nodeNormalRunedTime = nodeNormalRunedTime;
    }
}